name: CI Workflow for push and pull

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - run: echo "Triggered by a ${{ github.event_name }} on ${{ matrix.os }}"

      - run: python demo.py
